<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Modules\Clients\Entities\Dependents\AuthorizationCodes\Dependents\**" />
    <EmbeddedResource Remove="Modules\Clients\Entities\Dependents\AuthorizationCodes\Dependents\**" />
    <None Remove="Modules\Clients\Entities\Dependents\AuthorizationCodes\Dependents\**" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Modules\Clients\Entities\Dependents\OauthTokens\DerivedTypes\RefreshTokens\Dependents\" />
  </ItemGroup>

</Project>
