<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Modules\Clients\Enumerations\" />
    <Folder Include="Modules\Clients\RequestHanlers\Commands\GenerateAccessToken\BaseType\" />
    <Folder Include="Modules\Clients\RequestHanlers\Queries\" />
    <Folder Include="Modules\Clients\Tools\Generators\" />
    <Folder Include="Modules\Scopes\Repositories\" />
    <Folder Include="Modules\Users\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Http.Abstractions" Version="2.3.13" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\AuthorizationServer.Domain\AuthorizationServer.Domain.csproj" />
  </ItemGroup>

</Project>
